---
- hosts: all
  become: true
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: latest
        update_cache: yes
      notify:
        - restart nginx

    - name: Install Tomcat
      apt:
        name: tomcat9
        state: latest
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: latest
        update_cache: yes

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
